export interface ITeamOption {
  tla: string;
  name: string;
}

export const ALL_TEAMS: ITeamOption[] = [
  { tla: 'BRA', name: 'Brasil' },
  { tla: 'ARG', name: 'Argentina' },
  { tla: 'FRA', name: 'França' },
  { tla: 'ENG', name: 'Inglaterra' },
  { tla: 'ESP', name: 'Espanha' },
  { tla: 'GER', name: 'Alemanha' },
  { tla: 'POR', name: 'Portugal' },
  { tla: 'NED', name: 'Holanda' },
  { tla: 'BEL', name: 'Bélgica' },
  { tla: 'URU', name: 'Uruguai' },
  { tla: 'COL', name: 'Colômbia' },
  { tla: 'MEX', name: 'México' },
  { tla: 'USA', name: 'Estados Unidos' },
  { tla: 'CAN', name: 'Canadá' },
  { tla: 'MAR', name: 'Marrocos' },
  { tla: 'SEN', name: 'Senegal' },
  { tla: 'JPN', name: 'Japão' },
  { tla: 'KOR', name: 'Coreia do Sul' },
  { tla: 'AUS', name: 'Austrália' },
  { tla: 'IRN', name: 'Irã' },
  { tla: 'SAU', name: 'Arábia Saudita' },
  { tla: 'CRO', name: 'Croácia' },
  { tla: 'SUI', name: 'Suíça' },
  { tla: 'DEN', name: 'Dinamarca' },
  { tla: 'SWE', name: 'Suécia' },
  { tla: 'POL', name: 'Polônia' },
  { tla: 'SRB', name: 'Sérvia' },
  { tla: 'UKR', name: 'Ucrânia' },
  { tla: 'TUR', name: 'Turquia' },
  { tla: 'NGA', name: 'Nigéria' },
  { tla: 'CMR', name: 'Camarões' },
  { tla: 'GHA', name: 'Gana' },
  { tla: 'CIV', name: 'Costa do Marfim' },
  { tla: 'EGY', name: 'Egito' },
  { tla: 'TUN', name: 'Tunísia' },
  { tla: 'ALG', name: 'Argélia' },
  { tla: 'ECU', name: 'Equador' },
  { tla: 'CRC', name: 'Costa Rica' },
  { tla: 'PAN', name: 'Panamá' },
  { tla: 'JAM', name: 'Jamaica' },
  { tla: 'PAR', name: 'Paraguai' },
  { tla: 'CHI', name: 'Chile' },
  { tla: 'PER', name: 'Peru' },
  { tla: 'VEN', name: 'Venezuela' },
  { tla: 'BOL', name: 'Bolívia' },
  { tla: 'NZL', name: 'Nova Zelândia' },
  { tla: 'QAT', name: 'Catar' },
  { tla: 'CHN', name: 'China' },
].sort((a, b) => a.name.localeCompare(b.name, 'pt-BR'));
