import { ITeam } from '../@types';

const PT_NAMES: Record<string, { name: string; shortName: string }> = {
  // América do Sul
  BRA: { name: 'Brasil',         shortName: 'Brasil'      },
  ARG: { name: 'Argentina',      shortName: 'Argentina'   },
  URU: { name: 'Uruguai',        shortName: 'Uruguai'     },
  COL: { name: 'Colômbia',       shortName: 'Colômbia'    },
  ECU: { name: 'Equador',        shortName: 'Equador'     },
  PER: { name: 'Peru',           shortName: 'Peru'        },
  VEN: { name: 'Venezuela',      shortName: 'Venezuela'   },
  BOL: { name: 'Bolívia',        shortName: 'Bolívia'     },
  PAR: { name: 'Paraguai',       shortName: 'Paraguai'    },
  CHI: { name: 'Chile',          shortName: 'Chile'       },

  // América do Norte e Central
  USA: { name: 'Estados Unidos', shortName: 'EUA'         },
  MEX: { name: 'México',         shortName: 'México'      },
  CAN: { name: 'Canadá',         shortName: 'Canadá'      },
  CRC: { name: 'Costa Rica',     shortName: 'Costa Rica'  },
  PAN: { name: 'Panamá',         shortName: 'Panamá'      },
  JAM: { name: 'Jamaica',        shortName: 'Jamaica'     },
  HON: { name: 'Honduras',       shortName: 'Honduras'    },
  SLV: { name: 'El Salvador',    shortName: 'El Salvador' },
  TRI: { name: 'Trinidad e Tobago', shortName: 'Trinidad' },
  GUA: { name: 'Guatemala',      shortName: 'Guatemala'   },
  CUB: { name: 'Cuba',           shortName: 'Cuba'        },
  HAI: { name: 'Haiti',          shortName: 'Haiti'       },

  // Europa
  FRA: { name: 'França',         shortName: 'França'      },
  GER: { name: 'Alemanha',       shortName: 'Alemanha'    },
  ESP: { name: 'Espanha',        shortName: 'Espanha'     },
  ENG: { name: 'Inglaterra',     shortName: 'Inglaterra'  },
  POR: { name: 'Portugal',       shortName: 'Portugal'    },
  ITA: { name: 'Itália',         shortName: 'Itália'      },
  NED: { name: 'Holanda',        shortName: 'Holanda'     },
  BEL: { name: 'Bélgica',        shortName: 'Bélgica'     },
  SUI: { name: 'Suíça',          shortName: 'Suíça'       },
  AUT: { name: 'Áustria',        shortName: 'Áustria'     },
  DEN: { name: 'Dinamarca',      shortName: 'Dinamarca'   },
  SWE: { name: 'Suécia',         shortName: 'Suécia'      },
  NOR: { name: 'Noruega',        shortName: 'Noruega'     },
  POL: { name: 'Polônia',        shortName: 'Polônia'     },
  CRO: { name: 'Croácia',        shortName: 'Croácia'     },
  SRB: { name: 'Sérvia',         shortName: 'Sérvia'      },
  UKR: { name: 'Ucrânia',        shortName: 'Ucrânia'     },
  TUR: { name: 'Turquia',        shortName: 'Turquia'     },
  GRE: { name: 'Grécia',         shortName: 'Grécia'      },
  ROU: { name: 'Romênia',        shortName: 'Romênia'     },
  HUN: { name: 'Hungria',        shortName: 'Hungria'     },
  CZE: { name: 'Rep. Tcheca',    shortName: 'Rep. Tcheca' },
  SVK: { name: 'Eslováquia',     shortName: 'Eslováquia'  },
  SVN: { name: 'Eslovênia',      shortName: 'Eslovênia'   },
  SCO: { name: 'Escócia',        shortName: 'Escócia'     },
  WAL: { name: 'País de Gales',  shortName: 'Gales'       },
  IRL: { name: 'Irlanda',        shortName: 'Irlanda'     },
  ALB: { name: 'Albânia',        shortName: 'Albânia'     },
  GEO: { name: 'Geórgia',        shortName: 'Geórgia'     },
  ISL: { name: 'Islândia',       shortName: 'Islândia'    },
  FIN: { name: 'Finlândia',      shortName: 'Finlândia'   },
  BUL: { name: 'Bulgária',       shortName: 'Bulgária'    },
  MNE: { name: 'Montenegro',     shortName: 'Montenegro'  },
  NMK: { name: 'Macedônia',      shortName: 'Macedônia'   },
  BIH: { name: 'Bósnia',         shortName: 'Bósnia'      },
  LUX: { name: 'Luxemburgo',     shortName: 'Luxemburgo'  },

  // África
  MAR: { name: 'Marrocos',       shortName: 'Marrocos'    },
  SEN: { name: 'Senegal',        shortName: 'Senegal'     },
  NGA: { name: 'Nigéria',        shortName: 'Nigéria'     },
  CMR: { name: 'Camarões',       shortName: 'Camarões'    },
  GHA: { name: 'Gana',           shortName: 'Gana'        },
  EGY: { name: 'Egito',          shortName: 'Egito'       },
  TUN: { name: 'Tunísia',        shortName: 'Tunísia'     },
  CIV: { name: 'Costa do Marfim',shortName: 'C. Marfim'   },
  ALG: { name: 'Argélia',        shortName: 'Argélia'     },
  ZAF: { name: 'África do Sul',  shortName: 'África do Sul'},
  MLI: { name: 'Mali',           shortName: 'Mali'        },
  BFA: { name: 'Burkina Faso',   shortName: 'Burkina Faso'},
  COD: { name: 'DR Congo',       shortName: 'DR Congo'    },
  MOZ: { name: 'Moçambique',     shortName: 'Moçambique'  },

  // Ásia
  JPN: { name: 'Japão',          shortName: 'Japão'       },
  KOR: { name: 'Coreia do Sul',  shortName: 'Coreia do Sul'},
  IRN: { name: 'Irã',            shortName: 'Irã'         },
  SAU: { name: 'Arábia Saudita', shortName: 'Ar. Saudita' },
  AUS: { name: 'Austrália',      shortName: 'Austrália'   },
  QAT: { name: 'Catar',          shortName: 'Catar'       },
  CHN: { name: 'China',          shortName: 'China'       },
  IDN: { name: 'Indonésia',      shortName: 'Indonésia'   },
  IRQ: { name: 'Iraque',         shortName: 'Iraque'      },
  JOR: { name: 'Jordânia',       shortName: 'Jordânia'    },
  UZB: { name: 'Uzbequistão',    shortName: 'Uzbequistão' },
  THA: { name: 'Tailândia',      shortName: 'Tailândia'   },
  UAE: { name: 'Emirados Árabes',shortName: 'EAU'         },
  BHR: { name: 'Barein',         shortName: 'Barein'      },
  KWT: { name: 'Kuwait',         shortName: 'Kuwait'      },
  OMN: { name: 'Omã',            shortName: 'Omã'         },
  SYR: { name: 'Síria',          shortName: 'Síria'       },
  KGZ: { name: 'Quirguistão',    shortName: 'Quirguistão' },
  TJK: { name: 'Tajiquistão',    shortName: 'Tajiquistão' },
  MYS: { name: 'Malásia',        shortName: 'Malásia'     },
  PHI: { name: 'Filipinas',      shortName: 'Filipinas'   },
  VIE: { name: 'Vietnã',         shortName: 'Vietnã'      },
  PRK: { name: 'Coreia do Norte',shortName: 'Coreia do Norte'},

  // Oceania
  NZL: { name: 'Nova Zelândia',  shortName: 'Nova Zelândia'},
  FIJ: { name: 'Fiji',           shortName: 'Fiji'        },
  PNG: { name: 'Papua Nova Guiné',shortName: 'Papua'      },
  SOL: { name: 'Ilhas Salomão',  shortName: 'Ilhas Salomão'},
  VAN: { name: 'Vanuatu',        shortName: 'Vanuatu'     },
};

export function translateTeam(team: ITeam): ITeam {
  const pt = PT_NAMES[team.tla];
  if (!pt) return team;
  return { ...team, name: pt.name, shortName: pt.shortName };
}
